console.log("javascript")
document.write("javascript class")
console.log('my name')
console.log("learning is fun")
console.log(`larva`)
console.log('i\'m here')
console.log(typeof("yes"))
console.log(typeof(2.5))
console.log(true)
console.log(null)
console.log(1.5+3.75)
console.log('Abdulwariz '+ 'Yusuff')
console.log(4-2)
console.log(3**2)
console.log(5%2)
console.log(2%5)
console.log(3+1*2)

console.log(true&&true)
console.log(true&&false)
console.log(false&&true)
console.log(false&&false)

console.log(true||true)
console.log(true||false)
console.log(false||true)
console.log(false||false)

console.log(!true)
console.log(!false)
console.log(!true&&true||false) 
console.log(5>2)
console.log(5<2)
console.log(5<=5)
console.log(5=='5')
console.log(5==='5')
console.log(5!='5');
(5<2)? console.log('5 is less than 2') : console.log('5 is greater than 2')
let firstName='Abdulwariz'
console.log(firstName)
const lastName='Yusuff'
console.log(lastName)
firstName='Demj3ez'
console.log(firstName)